Repository Code-4-Community/lucys-love-bus-frontend, pull requests merged in 2021-04, with the labels that each got.

#129 Create Users Directory
  package-lock.json
  package.json
  src/App.tsx
  src/api/protectedApiClient.ts
  src/components/UserInfoTable.tsx
  src/containers/userDirectory/index.tsx
  src/utils/colors.tsx
Labels: medium

#130 Added Bug Report Sticky Footer
  src/App.tsx
  src/components/BugReportFooter.tsx
Labels: small

#133 Clear In-Memory Redux Store on Logout
  src/components/navbar/index.tsx
Labels: small

#136 Load DOB data to initialize form data
  src/containers/setContacts/index.tsx
Labels: bug, small

#140 Ryanjung create edit delete announcements
  src/App.tsx
  src/api/protectedApiClient.ts
  src/components/AnnouncementCard.tsx
  src/components/AnnouncementForm.tsx
  src/components/AnnouncementModal.tsx
  src/components/event-details/EventDetails.tsx
  src/components/event-listing/EventListing.tsx
  src/containers/announcements/ducks/types.ts
  src/containers/announcements/test/selectors.test.ts
  src/containers/createAnnouncement/index.tsx
  src/containers/deleteAnnouncement/index.tsx
  src/containers/singleEvent/index.tsx
Labels: medium

#131 Settings Hub Page and Better User Dropdown
  src/App.tsx
  src/components/navbar/index.tsx
  src/containers/changePassword/index.tsx
  src/containers/settings/index.tsx
Labels: medium

#134 Create/Edit/Delete Event
  src/App.tsx
  src/api/protectedApiClient.ts
  src/components/EventsForm.tsx
  src/components/event-details/EventDetails.tsx
  src/components/event-listing/EventListing.tsx
  src/containers/createEvent/ducks/types.ts
  src/containers/createEvent/index.tsx
  src/containers/deleteEvent/index.tsx
  src/containers/editEvent/index.tsx
  src/containers/singleEvent/index.tsx
  src/store.ts
  src/utils/colors.tsx
Labels: medium

#144 Changed signup flow pictures
  src/components/SignupDirectory.tsx
Labels: small
